steps:
      - uses: actions/checkout@v3

      - name: Push app.py to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Instalar la librería de Hugging Face
          pip install huggingface_hub
          
          # 2. Subir SOLO el archivo app.py (o los que tú quieras)
          python -c "
          from huggingface_hub import HfApi
          api = HfApi()
          api.upload_file(
              path_or_fileobj='app.py',
              path_in_repo='app.py',
              repo_id='MGC1991MF/DermaRAG-DEMO',
              repo_type='space',
              token='$HF_TOKEN'
          )
          "
